trigger:
  - main

variables:
  deploymentLocation: 'eastus'
  azureResourceManagerConnection: 'az-dw-arm-sc'

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Dev_Deployment
    displayName: 'DEV Deployment'
    variables:
      resourcePrefix: 'azdwudacitydev'

    jobs:
      - deployment: Deploy_DEV_Environment
        displayName: 'DEV: Deploy resources'
        environment: 'Azure Data Warehouse - DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - template: pipeline-templates/deploy-data-platform-resources.yml
                  parameters:
                    environmentName: 'DEV'
                    resourcePrefix: $(resourcePrefix)
                    deploymentLocation: $(deploymentLocation)
                    azureResourceManagerConnection: $(azureResourceManagerConnection)
                    adminGroupObjectId: $(SynapseAdminObjectId)
