trigger:
  - main

variables:
  - name: deploymentLocation
    value: 'eastus'

  - name: azureResourceManagerConnection
    value: 'az-dw-arm-sc'

  - name: resourcePrefix
    value: 'azdwudacitydev'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - template: pipeline-templates/deploy-data-platform-resources.yml
    parameters:
      environmentName: 'DEV'
      resourcePrefix: $(resourcePrefix)
      deploymentLocation: $(deploymentLocation)
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      adminGroupObjectId: $(SynapseAdminObjectId)