trigger:
  - main

parameters:
  - name: isRelease
    displayName: 'Trigger a release to TEST'
    type: boolean
    default: 'false'

variables:
  deploymentLocation: 'eastus'
  azureResourceManagerConnection: 'az-dw-arm-sc'
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

resources:
  repositories:
    - repository: workspace_publish
      type: github
      endpoint: MaxBoykoII
      name: MaxBoykoII/azure-data-warehouse
      ref: workspace_publish

pool:
  vmImage: ubuntu-latest

stages:
  - stage: DEV_Deployment
    displayName: 'DEV Deployment'
    condition: and(eq(variables.isMain, 'true'), not(eq(parameters.isRelease, 'true')))
    variables:
      resourcePrefix: 'azdwudacitydev'

    jobs:
      - deployment: Deploy_DEV_Environment
        displayName: 'DEV: Deploy resources'
        environment: 'Azure Data Warehouse - DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: pipeline-templates/deploy-data-platform-resources.yml
                  parameters:
                    environmentName: 'DEV'
                    resourcePrefix: $(resourcePrefix)
                    deploymentLocation: $(deploymentLocation)
                    azureResourceManagerConnection: $(azureResourceManagerConnection)
                    adminGroupObjectId: $(SynapseAdminObjectId)
                    integrateWithSourceControl: 'yes'

  - stage: TEST_Deployment
    displayName: 'TEST Deployment'
    condition: and(eq(variables.isMain, 'true'), eq(parameters.isRelease, 'true'))
    variables:
      resourcePrefix: 'azdwudacitytest'

    jobs:
      - deployment: Deploy_TEST_Environment
        displayName: 'TEST: Deploy resources'
        environment: 'Azure Data Warehouse - TEST'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: pipeline-templates/deploy-data-platform-resources.yml
                  parameters:
                    environmentName: 'TEST'
                    resourcePrefix: $(resourcePrefix)
                    deploymentLocation: $(deploymentLocation)
                    azureResourceManagerConnection: $(azureResourceManagerConnection)
                    adminGroupObjectId: $(SynapseAdminObjectId)
                    integrateWithSourceControl: 'no'
