trigger:
  - main

variables:
  - name: deploymentLocation
    value: uswest2

  - name: azureResourceManagerConnection
    value: az-dw-arm-sc

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - displayName: "TEST: Transpile bicep"
    bash: az bicep build --file ./deployment/main.bicep

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: "TEST: Deploy Main Template"
    inputs:
      azureResourceManagerConnection: $(azureResourceManagerConnection)
      deploymentScope: "Subscription"
      location: $(deploymentLocation)
      templateLocation: "Linked artifact"
      csmFile: "./deployment/main.json"
      deploymentMode: "Incremental"
